name: Deploy Github Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: npm install and build
        run: |
          npm install
          npm run build

      - uses: actions/upload-artifact@master
        with:
          name: vite artifacts
          path: "public"
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@master
        with:
          name: vite artifacts
          path: "public"

      - name: Deploy
        uses: actions/deploy-pages@v1
