name: Deploy Github Pages

permissions:
  pages: write
  id-token: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: npm install and build
        run: |
          npm install
          npm run build

      - uses: actions/upload-artifact@master
        with:
          name: vite artifacts
          path: dist
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@master
        with:
          name: vite artifacts
          path: dist

      - name: Deploy
        uses: actions/deploy-pages@v1
        with:
          emit_telemetry: false
          token: ${{secrets.GITHUB_TOKEN}}
          timeout: 600000
          error_count: 10
          reporting_interval: 5000
