name: Deploy Github Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-lastest, windows-2016]
        node-version: [12.x, 14.x]

    install and build:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Instal and build depends
      - name: npm install and build
        run: |
          npm install
          npm run build

      # Upload artifact
      - uses: actions/upload-artifact@master
        with:
          name: Upload artifacts
          path: "."
    
    deploy:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Download artifact
      - uses: actions/download-artifact@master
        with:
          name: Download artifacts
          path: "."
      
      # Deploy site
      - name: Deploy
        uses: actions/deploy-pages@v1
