name: Deploy Github Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-lastest, windows-2016]
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v3
      
      - name: npm install and build
        run: |
          npm install
          npm run build

      - uses: actions/upload-artifact@master
        with:
          name: Upload artifacts
          path: "."
  
  deploy:
    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        os: [ubuntu-lastest, windows-2016]
        node-version: [12.x, 14.x]
    
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@master
        with:
          name: Download artifacts
          path: "."
      
      - name: Deploy
        uses: actions/deploy-pages@v1
